### PR TITLE
rubaltic: avoid redirect and bypass application cache

### PR DESCRIPTION
**Pull request by timespace42**

### CODE REVIEW

**Review by SlenkyDev — CHANGES_REQUESTED** [review]
Hi there, please also add the new patern into the root index.html file.
Also, I'd like to please ask you to build the website using the guide in README.md before submiting a pull-request.

Thank you!

**Comment by timespace42** [comment]
> Hi there, please also add the new patern into the root index.html file. Also, I'd like to please ask you to build the website using the guide in README.md before submiting a pull-request.
> 
> Thank you!

Will do for now, however building PR and keeping `/dist` under version control makes no sense. Is it something you can re-configure @SlenkyDev ?

**Comment by SlenkyDev** [comment]
> > Hi there, please also add the new patern into the root index.html file. Also, I'd like to please ask you to build the website using the guide in README.md before submiting a pull-request.
> > Thank you!
> 
> Will do for now, however building PR and keeping `/dist` under version control makes no sense. Is it something you can re-configure @SlenkyDev ?

I wasn't the one who originally made it that way as I didn't make the frontend, @OLIMINATOR did.
I'll let him know.

**Comment by timespace42** [comment]
@SlenkyDev @OLIMINATOR here is what changed since review:
1. Prettier fixed and now applies automatically on local env, most of the changes are automatic formatting
2. Changed flood results refresh to happen 2 times per second
3. Removed statics from index.html

**Comment by SlenkyDev** [comment]
Should be good 👍

**Pull request merged**
