### PR TITLE
Adding few more targets

### PR DESCRIPTION
**Pull request by fabri86**
Added following targets:

https://yandex.ru/
https://sputniknews.com/
https://inosmi.ru/
https://gazeta.ru/
https://kommersant.ru/
https://rubaltic.ru/
https://ura.news/
https://radiokp.ru/
https://echo.msk.ru/
https://life.ru/

Notes:
Sites like yandex seems to be a tough nut to crack (They require a recaptcha to continue).
Not sure if it is gonna work

### CODE REVIEW

**Review by SlenkyDev — CHANGES_REQUESTED** [review]
Hi there, you need to also add the sites inside of the <script> tag, in the targets list ext., not just the stats placeholders.

Also, once done, please also add the changes to the dist/index.html file.
Thanks!

**Comment by fabri86** [comment]
@SlenkyDev thanks!

I think they are in both places already (stats and script tags).
If that is not the case, could you please clarify what I missed?

Dist file updated ;)
Thanks

**Review by SlenkyDev — APPROVED** [review]
Thank you! I missed the files inside the script tag, sorry!

**Comment by fabri86** [comment]
Thanks! 🎉

**Pull request merged**
